-- CREATE PROCEDURE my_version ()
-- BEGIN
 -- SELECT VERSION();
-- END

DROP FUNCTION IF EXISTS get_version;

CREATE FUNCTION get_version()
RETURNS VARCHAR(255) DETERMINISTIC
BEGIN
	RETURN VERSION();
END

